apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: sonarqube
  # annotations:
  #   haproxy.org/check: "true"
  #   haproxy.org/forwarded-for: "true"
  #   haproxy.org/load-balance: "roundrobin"
  #   haproxy.org/cookie-persistence: "mycookie"
spec:
  selector:
      app: sonarqube
  ports:
  - name: port-sonar
    port: 9000
    protocol: TCP
    targetPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube-db
  name: sonarqube-db
  namespace: sonarqube
spec:
  selector:
      app: sonarqube-db
  ports:
  - name: port-db
    port: 5432
    protocol: TCP
    targetPort: 5432